### ISSUE TITLE
Broken using React 0.14 and NPM 2

### ISSUE THREAD

**Issue by pcwinters** [algolia/react-element-to-jsx-string#24]
`react-element-to-jsx-string` lists React 0.15 as a dependency, which npm 2 will complain about if an application uses React 0.14. 

FYI, I was pulling `"jsx-chai": "^2.0.0"` which in turn pulls `react-element-to-jsx-string`. npm 2 installs React 0.15 for you and then errors on invalid peer dependencies, because everything else in the application expects 0.14.

**Comment by vvo** [comment]
should be fixed now, let me know

**Comment by pcwinters** [comment]
fixed. ty :+1:

**Comment by mgibeau** [comment]
Sorry to resurrect this but, I'm having the same issue while using `chai-jsx`. Using npm 3 grabs react-addons-test-utils@15.0.1

Not sure if `||` is a correct expectation for a dependency
https://github.com/algolia/react-element-to-jsx-string/commit/7347b7112bd2fa2b73cb17fccd963aa623858fdd#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R36

**Comment by vvo** [comment]
Can you create a testing repo that is reproducing this so we can fix it? Or do you have a fix in mind?

**Comment by mgibeau** [comment]
https://github.com/mgibeau/react-element-to-jsx-string_issue_24_sample

As for a fix, it seems there are no clear cut solutions in this particular case. I think the most straight forward is to simply release separate versions that target different react versions (e.g.: 2.0 -> 0.14 vs 3.0 -> 15).

Moving `react-addons-test-utils` to a peer dependency would work too, but would kinda break backward compatibility.

Otherwise, I guess a `postinstall` script that figures out the react version and conditionally install the `react-addons-test-utils` is also possible, but this seems a bit overkill.
