### ISSUE TITLE
sortobject update (1.1.0) breaks webpack

### ISSUE THREAD

**Issue by dvkndn** [algolia/react-element-to-jsx-string#25]
[sortobject](https://github.com/bevry/sortobject) are updated to 1.1.0 today, and it uses [editions](https://github.com/bevry/editions) to select correct build for consumer environment.

However, it seems webpack cannot work correctly with this, which throw an error "cannot find package.json".

Reproduce: npm install react-element-to-jsx-string. Make sure that it also installs sortobject@1.1.0. Then use it like in Readme to see error.

Temporary Solution: Remove sortobject and reinstall sortobject@1.0.0

**Comment by tommcgurl** [comment]
👍

**Comment by balupton** [comment]
https://github.com/bevry/sortobject/issues/3

**Comment by tommcgurl** [comment]
👍 😄 Nice thanks to @balupton this is now fixed with version `1.1.0` of `sortobject`. Thanks to @dvkndn for opening the issue.

**Comment by vvo** [comment]
Sooo we can close this?

**Comment by balupton** [comment]
I'd say so. I don't have ability to.

**Comment by vvo** [comment]
Thanks all!

**Comment by wesleytodd** [comment]
Recently we tried to integrate this module into one of our services.  `editions` makes an assumption that the javascript is in a `node_modules` directory and that you can require in the `package.json`.  In our production environments we use `browserify` to bundle up our entire application into a single file for deployment, thus breaking the require statement [here](https://github.com/bevry/editions/blob/master/source/index.js#L182).  Seems very similar to this issue.

We cannot remove this from our build process because the number of files in our `node_modules`  caused us to run out of disk inodes on some of our prod machines and also made our deployments take MUCH longer.  What would be your suggestion to use this module?  Pin back the version? 

Has there been any talk about not using `sortobject`/`editions` dependency since it is doing a pretty non-standard thing?  I know shipping "fat" modules is cool these days, but node core will be figuring this out, soon hopefully, so adding a homegrown solution just for sorting of object keys seems like a bad idea for this module.  Not criticizing, just asking :)

Commented on https://github.com/bevry/sortobject/issues/7 as well (for reference).

**Comment by Haroenv** [comment]
I’m wondering if we could fix this in the react-element-to-jsx-string package itself by depending on `https://github.com/bevry/sortobject/blob/master/source/index.js` directly. What do you think @vvo

**Comment by wesleytodd** [comment]
To be hones, I cant see what the editions module is even doing for the `sortobject` package, seems like it just has that one version, right?

**Comment by balupton** [comment]
Sortobject and editions author here.

You can always reach out besides deciding a mutiny.

The browser package.json field should be respected and used by browserify.

**Comment by Haroenv** [comment]
Good point. I was more suggesting it as a temporary workaround

**Comment by wesleytodd** [comment]
Hey @balupton, sorry if it came across as mutiny, I didn't intend it as that at all!  Not being familiar with that package and what it was doing I was just asking because it didn't appear to be doing anything.  I could totally be wrong, thus my question about it only having one version.  Also, I did comment on an issue on `sortobject` first :) https://github.com/bevry/sortobject/issues/7

In this case, we are using browserify's `--node` flag to bundle for the node runtime.  So it purposely ignores the `browser` field.  Because the require is dynamic, browserify ignores it.  Obviously we could add a forced require in our build for this `package.json` file, but that does not seem like a good idea.  Any advice would be most welcome!

**Comment by vvo** [comment]
This seems like not an issue of our own package. Also I loved the

> You can always reach out besides deciding a mutiny.

Because I thought

![giphy 3](https://user-images.githubusercontent.com/123822/27032135-a2ebc334-4f73-11e7-90b9-2cf7a0b6a597.gif)

**Comment by vvo** [comment]
(Also please open new issues instead of reviving old ones, always easier)
